-- AlterEnum
ALTER TYPE "NotifType" ADD VALUE 'ADMIN_WARNING';
ALTER TYPE "NotifType" ADD VALUE 'ADMIN_HIDE_NOTICE';
ALTER TYPE "NotifType" ADD VALUE 'ADMIN_DELETE_NOTICE';
ALTER TYPE "NotifType" ADD VALUE 'ADMIN_BROADCAST';
